logging:
  level:
    com.unicorn.phonebill.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.data.redis: INFO
    org.springframework.web.reactive: WARN
    reactor.netty.http.client: WARN
    io.netty.handler.ssl: WARN
    root: WARN
