# API Gateway 개발 환경 설정

server:
  port: 8080

spring:

  # Cloud Gateway 개발환경 설정
  cloud:
    gateway:
      default-filters: []
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: 
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "https://localhost:*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 86400  # 24시간

  # 개발도구 설정
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
    livereload:
      enabled: true

# JWT 설정 (개발용 - 더 긴 유효시간)
app:
  jwt:
    secret: ${JWT_SECRET:dev-phonebill-api-gateway-jwt-secret-key-256-bit-minimum-length-for-development}
    access-token-validity-in-seconds: 3600   # 1시간 (개발편의성)
    refresh-token-validity-in-seconds: 172800 # 48시간 (개발편의성)

# Circuit Breaker 설정 (개발환경 - 더 관대한 설정)
resilience4j:
  circuitbreaker:
    instances:
      auth-service-cb:
        failure-rate-threshold: 80  # 개발환경은 더 관대한 임계값
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      bill-service-cb:
        failure-rate-threshold: 80
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      product-service-cb:
        failure-rate-threshold: 80
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
      kos-mock-cb:
        failure-rate-threshold: 90
        wait-duration-in-open-state: 5s
        sliding-window-size: 5
        minimum-number-of-calls: 2

# Actuator 설정 (개발환경 - 모든 엔드포인트 노출)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 개발환경에서는 모든 엔드포인트 노출
      base-path: /actuator
  endpoint:
    health:
      show-details: always  # 개발환경에서는 상세 정보 항상 표시
    shutdown:
      enabled: true  # 개발환경에서만 활성화
    beans:
      enabled: true
    env:
      enabled: true
    configprops:
      enabled: true

# 로깅 설정 (개발환경 - 더 상세한 로그)
logging:
  level:
    com.unicorn.phonebill.gateway: ${LOG_LEVEL_GATEWAY:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_SPRING_CLOUD_GATEWAY:DEBUG}
    org.springframework.data.redis: ${LOG_LEVEL_SPRING_DATA_REDIS:DEBUG}
    org.springframework.web.reactive: ${LOG_LEVEL_SPRING_WEB_REACTIVE:DEBUG}
    reactor.netty.http.client: ${LOG_LEVEL_REACTOR_NETTY_HTTP_CLIENT:DEBUG}
    io.netty.handler.ssl: ${LOG_LEVEL_IO_NETTY_HANDLER_SSL:WARN}
    root: ${LOG_LEVEL_ROOT:INFO}
  file:
    name: ${LOG_FILE:logs/api-gateway.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:7}

# OpenAPI 설정 (개발환경)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true  # 개발환경에서 Try it out 활성화
    urls:
      - name: Auth Service (Dev)
        url: http://localhost:8081/v3/api-docs
      - name: Bill Service (Dev)
        url: http://localhost:8082/v3/api-docs
      - name: Product Service (Dev)
        url: http://localhost:8083/v3/api-docs
      - name: KOS Mock Service (Dev)
        url: http://localhost:8084/v3/api-docs

# CORS 설정 (개발환경 - 더 관대한 설정) - 이미 위에서 설정됨

# 개발환경 특성 설정
debug: false
trace: false

# 애플리케이션 정보 (개발환경)
info:
  app:
    environment: development
    debug-mode: enabled
    hot-reload: enabled