# API Gateway 기본 설정
# Spring Boot 3.2 + Spring Cloud Gateway

server:
  port: ${SERVER_PORT:8080}
  netty:
    connection-timeout: ${SERVER_NETTY_CONNECTION_TIMEOUT:30s}
    idle-timeout: ${SERVER_NETTY_IDLE_TIMEOUT:60s}
  http2:
    enabled: true
  # HTTP 헤더 크기 제한 설정
  max-http-header-size: 64KB
  max-http-request-header-size: 64KB

spring:
  application:
    name: api-gateway
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      # HTTP 관련 설정
      httpclient:
        pool:
          max-connections: 1000
          max-idle-time: 30s
        response-timeout: 60s
        connect-timeout: 5000
      
      default-filters:
        - name: AddRequestHeader
          args:
            name: X-Gateway-Request
            value: API-Gateway
        - name: AddResponseHeader
          args:
            name: X-Gateway-Response
            value: API-Gateway
      
      # Global CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      # Discovery 설정 비활성화 (직접 라우팅 사용)
      discovery:
        locator:
          enabled: false

  # JSON 설정
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# JWT 토큰 설정
jwt:
  secret: ${JWT_SECRET:}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:180000}
  refresh-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:86400000}

# 서비스 URL 설정
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  bill-service:
    url: ${BILL_SERVICE_URL:http://localhost:8082}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
  kos-mock:
    url: ${KOS_MOCK_URL:http://localhost:8084}

# Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    instances:
      auth-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
      bill-service-cb:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 30s
        sliding-window-size: 20
        minimum-number-of-calls: 10
      product-service-cb:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 30s
        sliding-window-size: 20
        minimum-number-of-calls: 10
      kos-mock-cb:
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        minimum-number-of-calls: 5
  
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    gateway:
      enabled: true
  health:
    redis:
      enabled: false
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

# 로깅 설정
logging:
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan([%X{traceId:-},%X{spanId:-}]) %logger{36} - %msg%n"


# 애플리케이션 정보
info:
  app:
    name: PhoneBill API Gateway
    description: 통신요금 관리 서비스 API Gateway
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17