# 로깅 설정 (개발환경 - 더 상세한 로그)
logging:
  level:
    com.unicorn.phonebill.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty.handler.ssl: DEBUG
    root: DEBUG
