# 통신요금 관리 서비스 - Bill Service 기본 설정
# 공통 설정 및 개발환경 기본값
#
# @author 이개발(백엔더)
# @version 1.0.0
# @since 2025-09-08

spring:
  application:
    name: bill-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST:20.249.107.185}:${DB_PORT:5432}/${DB_NAME:product_change}
    username: ${DB_USERNAME:product_user}
    password: ${DB_PASSWORD:product_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  # JPA 설정
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          provider_disables_autocommit: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1
      database: ${REDIS_DATABASE:2}

  # Cache 개발 설정 (TTL 단축)
  cache:
    redis:
      time-to-live: 3600000 # 1시간 (개발환경에서 단축)

  # Jackson 설정
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

# 서버 설정
server:
  port: ${SERVER_PORT:8082}
  # HTTP 헤더 크기 제한 설정
  max-http-header-size: 64KB
  max-http-request-header-size: 64KB
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# KOS 시스템 연동 설정
kos:
  base-url: ${KOS_BASE_URL:http://localhost:8084}
  connect-timeout: ${KOS_CONNECT_TIMEOUT:5000}
  read-timeout: ${KOS_READ_TIMEOUT:30000}
  max-retries: ${KOS_MAX_RETRIES:3}
  retry-delay: ${KOS_RETRY_DELAY:1000}
  
  # Circuit Breaker 설정
  circuit-breaker:
    failure-rate-threshold: ${KOS_CB_FAILURE_RATE:0.5}
    slow-call-duration-threshold: ${KOS_CB_SLOW_DURATION:10000}
    slow-call-rate-threshold: ${KOS_CB_SLOW_RATE:0.5}
    sliding-window-size: ${KOS_CB_WINDOW_SIZE:10}
    minimum-number-of-calls: ${KOS_CB_MIN_CALLS:5}
    permitted-number-of-calls-in-half-open-state: ${KOS_CB_HALF_OPEN_CALLS:3}
    wait-duration-in-open-state: ${KOS_CB_OPEN_DURATION:60000}

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
  show-actuator: false
  writer-with-default-pretty-printer: true
  paths-to-exclude: /actuator/**

# CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# JWT 보안 설정
jwt:
  secret: ${JWT_SECRET:}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:1800}
  refresh-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:86400}

# 로깅 설정
logging:
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "${LOG_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
  file:
    name: logs/bill-service.log
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
