apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
  namespace: phonebill-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DDL_AUTO: "validate"
  
  # JWT 설정 - 프로덕션 보안 강화
  JWT_ACCESS_EXPIRATION: "1800000"    # 30분 (1800초)
  JWT_REFRESH_EXPIRATION: "43200000"  # 12시간 (43200초)
  
  # 로깅 설정
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_COM_PHONEBILL: "INFO"
  
  # 캐시 설정
  CACHE_TTL: "3600"  # 1시간