apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: user-service
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: bill-service
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: kos-mock
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"