apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: phonebill-prod

namespace: phonebill-prod

resources:
  - ../../base

commonLabels:
  environment: prod

images:
  - name: acrdigitalgarage01.azurecr.io/phonebill/api-gateway
    newTag: prod-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/user-service
    newTag: prod-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/bill-service
    newTag: prod-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/product-service
    newTag: prod-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/kos-mock
    newTag: prod-latest

patches:
  # ConfigMap patches
  - path: configmap-common-patch.yaml
    target:
      kind: ConfigMap
      name: common-config
  
  # Secret patches
  - path: secret-common-patch.yaml
    target:
      kind: Secret
      name: common-secret
  - path: secret-user-service-patch.yaml
    target:
      kind: Secret
      name: user-service-secret
  - path: secret-bill-service-patch.yaml
    target:
      kind: Secret
      name: bill-service-secret
  - path: secret-product-service-patch.yaml
    target:
      kind: Secret
      name: product-service-secret
  
  # Ingress patches
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: phonebill-ingress
  
  # Deployment patches
  - path: deployment-api-gateway-patch.yaml
    target:
      kind: Deployment
      name: api-gateway
  - path: deployment-user-service-patch.yaml
    target:
      kind: Deployment
      name: user-service
  - path: deployment-bill-service-patch.yaml
    target:
      kind: Deployment
      name: bill-service
  - path: deployment-product-service-patch.yaml
    target:
      kind: Deployment
      name: product-service
  - path: deployment-kos-mock-patch.yaml
    target:
      kind: Deployment
      name: kos-mock