logging:
  level:
    com.phonebill: INFO

# 운영환경 모니터링 설정
metrics:
  export:
    prometheus:
      enabled: true
      step: 60s
  distribution:
    percentiles-histogram:
      http.server.requests: true
    percentiles:
      http.server.requests: 0.5, 0.9, 0.95, 0.99