apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            memory: "4096Mi"
            cpu: "4096m"
          limits:
            memory: "4096Mi"
            cpu: "4096m"