apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
data:
  CORS_ALLOWED_ORIGINS: "http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084,http://phonebill.20.214.196.128.nip.io"
  SPRING_PROFILES_ACTIVE: "dev"
  DDL_AUTO: "update"