apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway

spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-gateway
        image: acrdigitalgarage01.azurecr.io/phonebill/api-gateway:dev-latest
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi