apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phonebill-dev

resources:
  - ../../base

patches:
  - path: configmap-common-patch.yaml
    target:
      kind: ConfigMap
      name: cm-common
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: phonebill-ingress
  - path: secret-common-patch.yaml
    target:
      kind: Secret
      name: secret-common
  - path: secret-user-service-patch.yaml
    target:
      kind: Secret
      name: secret-user-service
  - path: secret-bill-service-patch.yaml
    target:
      kind: Secret
      name: secret-bill-service
  - path: secret-product-service-patch.yaml
    target:
      kind: Secret
      name: secret-product-service

images:
  - name: acrdigitalgarage01.azurecr.io/phonebill/api-gateway
    newTag: dev-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/user-service
    newTag: dev-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/bill-service
    newTag: dev-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/product-service
    newTag: dev-latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/kos-mock
    newTag: dev-latest

namePrefix: dev-

commonLabels:
  environment: dev