apiVersion: v1
kind: Secret
metadata:
  name: secret-common
type: Opaque
stringData:
  # Redis 설정 (개발 환경)
  REDIS_PASSWORD: "dev-redis-password"
  
  # JWT Secret Key (개발 환경용)
  JWT_SECRET: "dev-jwt-secret-key-for-phonebill-development"
  
  # 개발 환경용 공통 시크릿