apiVersion: v1
kind: Secret
metadata:
  name: secret-product-service
type: Opaque
stringData:
  # Product Service DB 접속 정보 (개발 환경)
  DB_PASSWORD: "productdb-dev-password"
  DB_URL: "jdbc:postgresql://product-change-postgres-dev-postgresql:5432/product_change_db"