apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
data:
  CORS_ALLOWED_ORIGINS: "https://phonebill-staging.example.com,https://phonebill.staging.example.com"
  SPRING_PROFILES_ACTIVE: "staging"
  DDL_AUTO: "validate"