apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: bill-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"