apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api-gateway
          image: acrdigitalgarage01.azurecr.io/phonebill-api-gateway:staging-latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "2048Mi"
              cpu: "2048m"