apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: user-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: bill-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: kos-mock
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "2048Mi"
            cpu: "2048m"