apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            memory: 512Mi
            cpu: 512m
          limits:
            memory: 2048Mi
            cpu: 2048m