apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: bill-service
          image: acrdigitalgarage01.azurecr.io/phonebill-bill-service:staging-latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "2048Mi"
              cpu: "2048m"