apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: kos-mock
          image: acrdigitalgarage01.azurecr.io/phonebill-kos-mock:staging-latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "2048Mi"
              cpu: "2048m"