apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: phonebill-staging

patches:
  # Common ConfigMap
  - target:
      kind: ConfigMap
      name: cm-common
    path: configmap-common-patch.yaml
  
  # Common Secret
  - target:
      kind: Secret
      name: secret-common
    path: secret-common-patch.yaml
  
  # Ingress
  - target:
      kind: Ingress
      name: phonebill-ingress
    path: ingress-patch.yaml
  
  # API Gateway
  - target:
      kind: Deployment
      name: api-gateway-deployment
    path: deployment-api-gateway-patch.yaml
  
  # User Service
  - target:
      kind: Deployment
      name: user-service-deployment
    path: deployment-user-service-patch.yaml
  - target:
      kind: Secret
      name: secret-user-service
    path: secret-user-service-patch.yaml
  
  # Bill Service
  - target:
      kind: Deployment
      name: bill-service-deployment
    path: deployment-bill-service-patch.yaml
  - target:
      kind: Secret
      name: secret-bill-service
    path: secret-bill-service-patch.yaml
  
  # Product Service
  - target:
      kind: Deployment
      name: product-service-deployment
    path: deployment-product-service-patch.yaml
  - target:
      kind: Secret
      name: secret-product-service
    path: secret-product-service-patch.yaml
  
  # KOS Mock
  - target:
      kind: Deployment
      name: kos-mock-deployment
    path: deployment-kos-mock-patch.yaml